---
# File : guix.yml

name: Guix/Guile 3.0

on:
  push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  x86_64-linux-gnu:
    name: "Guix build on latest commit for x86_64 system"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Guix cache"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/guix"
          # use a key that (almost) never matches
          key: "guix-cache-${{ github.sha }}"
          restore-keys: |
            guix-cache-
      - name: "Install Guix"
        run: |
         sudo apt-get update && sudo apt-get install guix
         guix pull
      - name: "Ensure no locale warning"
        run: |
          test -z "$(guix --version 2>&1 >/dev/null)"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Build project guile-ssh"
        run: |
          guix build --file=guix.scm guile-ssh
  aarch64-linux-gnu:
    name: "Guix build on latest commit for aarch64 system"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Guix cache"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/guix"
          # use a key that (almost) never matches
          key: "guix-cache-${{ github.sha }}"
          restore-keys: |
            guix-cache-
      - name: "Install Guix"
        run: |
         sudo apt-get update && sudo apt-get install guix
         guix pull
      - name: "Ensure no locale warning"
        run: |
          test -z "$(guix --version 2>&1 >/dev/null)"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Build project guile-ssh"
        run: |
          guix build --file=guix.scm guile-ssh

# End of guix.yml
...
